---
apiVersion: v1
kind: Pod
metadata:
  name: special-tribble
spec:
  containers:
    - name: echo-web
      image: hsmtkk/special-tribble:latest
      env:
        - name: HTTP_PORT
          value: "8000"
      ports:
        - name: web
          containerPort: 8000
          hostPort: 8000
          protocol: TCP
      volumeMounts:
        - name: log
          mountPath: /tmp
    - name: busybox
      image: busybox:latest
      command:
        - tail
      args:
        - -F
        - /tmp/log
      volumeMounts:
        - name: log
          mountPath: /tmp
  volumes:
    - name: log
      persistentVolumeClaim:
        claimName: log
