---
name: Go
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: test
        run: go test -v ./...

      - name: install-staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: run-staticcheck
        run: staticcheck ./...
